In [1]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

In [2]:
movies =pd.read_json('../movies/fixtures/movies_data_1000.json')

print(movies.shape)
movies.head(1)

(1000, 9)


movie_id  title release_date  popularity  vote_count  vote_average  \
0    436270  블랙 아담   2022-10-19   17020.709        1227           6.8   

                                            overview  \
0  기원전 가장 번성하고 위대한 고대 국가였지만 현재는 국제 군사 조직 인터갱의 독재 ...   

                        poster_path         genres  
0  /mEdMHGy1FfCUc7PskFO0tibm8jp.jpg  [28, 14, 878]

In [3]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   movie_id      1000 non-null   int64  
 1   title         1000 non-null   object 
 2   release_date  1000 non-null   object 
 3   popularity    1000 non-null   float64
 4   vote_count    1000 non-null   int64  
 5   vote_average  1000 non-null   float64
 6   overview      1000 non-null   object 
 7   poster_path   1000 non-null   object 
 8   genres        1000 non-null   object 
dtypes: float64(2), int64(2), object(5)
memory usage: 70.4+ KB


In [4]:
genre_list = {28: '액션', 12: '모험', 16: '애니메이션', 35: '코미디', 80: '범죄', 99: '다큐멘터리', 18: '드라마', 10751: '가족', 14: '판타지', 36: '역사', 27: '공포', 10402: '음악', 9648: '미스터리', 10749: '로맨스', 878: 'SF', 10770: 'TV 영화', 53: '스릴러', 10752: '전쟁', 37: '서부'}

In [5]:
movies['genres_literal'] = np.NaN

for i in range(1000):
    pk_list = movies['genres'][i]
    movies['genres_literal'][i] = ' '.join([genre_list.get(pk) for pk in pk_list])

In [6]:
movies.head()

movie_id           title release_date  popularity  vote_count  \
0    436270           블랙 아담   2022-10-19   17020.709        1227   
1    882598             스마일   2022-09-23    4674.437         734   
2    505642  블랙 팬서: 와칸다 포에버   2022-11-09    4248.617         855   
3    829280        에놀라 홈즈 2   2022-11-04    2096.361        1005   
4    948276        사라진 탄환 2   2022-11-10    1855.309          98   

   vote_average                                           overview  \
0           6.8  기원전 가장 번성하고 위대한 고대 국가였지만 현재는 국제 군사 조직 인터갱의 독재 ...   
1           6.8  기괴한 미소를 지으며 자신의 눈 앞에서 목숨을 끊는 환자를 목격한 정신과 의사 ‘로...   
2           7.5  국왕이자 블랙 팬서인 티찰라의 죽음 이후 수많은 강대국으로부터 위협을 받게 된 와칸...   
3           7.7  탐정이 된 후 첫 번째 사건을 수임한 에놀라. 하지만 실종된 소녀의 미스터리를 풀기...   
4           7.1  누명을 벗은 천재 자동차 정비공 리노. 이제 그의 마음속에 남은 목표는 단 하나. ...   

                        poster_path          genres genres_literal  
0  /mEdMHGy1FfCUc7PskFO0tibm8jp.jpg   [28, 14, 878]      액션 판타지 SF  
1  /8ncuVFt4e0M2NTTsoPtbxfWN5dO.jpg  [27, 9648, 53]    공포 미스터리 스릴러  
2  /3PCRWLeqp5y20k6XVzcamZR3BWF.jpg   [28, 12, 878]       액션 모험 SF  
3   /S6fDnntDjduIWuLW2GcqFasobD.jpg  [9648, 12, 80]     미스터리 모험 범죄  
4  /A84Usw0jwhh5RPAKZV7gwP532Fl.jpg    [28, 18, 53]     액션 드라마 스릴러

In [7]:
movies_df = movies

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(min_df=0, ngram_range=(1,2)) 
#ngram_range 단어 최대 2개까지 이용해서 피처를 생성, 단어1개 피처 단어 2개를 조합한 피처가 생성
count_vect.fit(movies_df['genres_literal'])

CountVectorizer(min_df=0, ngram_range=(1, 2))

In [9]:
count_vect.get_feature_names()

['sf',
 'sf 가족',
 'sf 공포',
 'sf 드라마',
 'sf 모험',
 'sf 미스터리',
 'sf 범죄',
 'sf 스릴러',
 'sf 애니메이션',
 'sf 액션',
 'sf 음악',
 'sf 코미디',
 'sf 판타지',
 'tv',
 'tv 영화',
 '가족',
 '가족 sf',
 '가족 tv',
 '가족 공포',
 '가족 드라마',
 '가족 로맨스',
 '가족 모험',
 '가족 서부',
 '가족 애니메이션',
 '가족 액션',
 '가족 음악',
 '가족 코미디',
 '가족 판타지',
 '공포',
 '공포 sf',
 '공포 tv',
 '공포 가족',
 '공포 드라마',
 '공포 미스터리',
 '공포 범죄',
 '공포 스릴러',
 '공포 액션',
 '공포 전쟁',
 '공포 코미디',
 '공포 판타지',
 '다큐멘터리',
 '다큐멘터리 음악',
 '드라마',
 '드라마 sf',
 '드라마 가족',
 '드라마 공포',
 '드라마 로맨스',
 '드라마 모험',
 '드라마 미스터리',
 '드라마 범죄',
 '드라마 스릴러',
 '드라마 액션',
 '드라마 역사',
 '드라마 전쟁',
 '드라마 코미디',
 '드라마 판타지',
 '로맨스',
 '로맨스 sf',
 '로맨스 가족',
 '로맨스 공포',
 '로맨스 드라마',
 '로맨스 스릴러',
 '로맨스 애니메이션',
 '로맨스 코미디',
 '로맨스 판타지',
 '모험',
 '모험 sf',
 '모험 tv',
 '모험 가족',
 '모험 공포',
 '모험 드라마',
 '모험 로맨스',
 '모험 미스터리',
 '모험 범죄',
 '모험 스릴러',
 '모험 애니메이션',
 '모험 액션',
 '모험 역사',
 '모험 음악',
 '모험 코미디',
 '모험 판타지',
 '미스터리',
 '미스터리 sf',
 '미스터리 공포',
 '미스터리 드라마',
 '미스터리 모험',
 '미스터리 범죄',
 '미스터리 스릴러',
 '미스터리 액션',
 '미스터리 코미디',
 '미스터리 판타지',
 '범죄',
 '범죄 공포',
 '

In [10]:
count_vect.vocabulary_ # 각 feature의 인덱스

{'액션': 129,
 '판타지': 184,
 'sf': 0,
 '액션 판타지': 143,
 '판타지 sf': 185,
 '공포': 28,
 '미스터리': 81,
 '스릴러': 105,
 '공포 미스터리': 33,
 '미스터리 스릴러': 87,
 '모험': 65,
 '액션 모험': 136,
 '모험 sf': 66,
 '범죄': 91,
 '미스터리 모험': 85,
 '모험 범죄': 73,
 '드라마': 42,
 '액션 드라마': 134,
 '드라마 스릴러': 50,
 '전쟁': 160,
 '전쟁 드라마': 161,
 '드라마 액션': 51,
 '애니메이션': 119,
 '코미디': 167,
 '가족': 15,
 '애니메이션 코미디': 127,
 '코미디 가족': 170,
 '액션 범죄': 138,
 '범죄 스릴러': 96,
 '공포 스릴러': 35,
 '스릴러 공포': 108,
 '판타지 코미디': 197,
 '미스터리 판타지': 90,
 '판타지 스릴러': 193,
 '판타지 액션': 195,
 '액션 코미디': 142,
 '판타지 모험': 191,
 '모험 가족': 68,
 '모험 액션': 76,
 '액션 sf': 130,
 '로맨스': 56,
 '로맨스 코미디': 63,
 '모험 판타지': 80,
 '코미디 스릴러': 177,
 '스릴러 액션': 115,
 '애니메이션 모험': 125,
 '모험 코미디': 79,
 '코미디 판타지': 183,
 '애니메이션 sf': 120,
 'sf 액션': 9,
 '가족 코미디': 26,
 '스릴러 모험': 110,
 '모험 공포': 69,
 '애니메이션 액션': 126,
 '액션 가족': 132,
 '코미디 sf': 168,
 '액션 스릴러': 139,
 '스릴러 미스터리': 111,
 '애니메이션 가족': 122,
 '다큐멘터리': 40,
 '가족 판타지': 27,
 '범죄 드라마': 93,
 '가족 액션': 24,
 '범죄 코미디': 99,
 '코미디 드라마': 173,
 '로맨스 드라마': 60,
 '스릴러 판타지

In [11]:
# 장르변환
genre_mat = count_vect.transform(movies_df['genres_literal'])
print(genre_mat.shape)

(1000, 198)


In [12]:
type(genre_mat)

scipy.sparse._csr.csr_matrix

In [13]:
genre_mat.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
pd.DataFrame(genre_mat.toarray(), columns=count_vect.get_feature_names())

sf  sf 가족  sf 공포  sf 드라마  sf 모험  sf 미스터리  sf 범죄  sf 스릴러  sf 애니메이션  sf 액션  \
0     1      0      0       0      0        0      0       0         0      0   
1     0      0      0       0      0        0      0       0         0      0   
2     1      0      0       0      0        0      0       0         0      0   
3     0      0      0       0      0        0      0       0         0      0   
4     0      0      0       0      0        0      0       0         0      0   
..   ..    ...    ...     ...    ...      ...    ...     ...       ...    ...   
995   0      0      0       0      0        0      0       0         0      0   
996   1      0      0       0      0        0      0       0         0      0   
997   0      0      0       0      0        0      0       0         0      0   
998   0      0      0       0      0        0      0       0         0      0   
999   0      0      0       0      0        0      0       0         0      0   

     ...  판타지 공포  판타지 드라마  판타지 로맨스  판타지 모험  판타지 미스터리  판타지 스릴러  판타지 애니메이션  \
0    ...       0        0        0       0         0        0          0   
1    ...       0        0        0       0         0        0          0   
2    ...       0        0        0       0         0        0          0   
3    ...       0        0        0       0         0        0          0   
4    ...       0        0        0       0         0        0          0   
..   ...     ...      ...      ...     ...       ...      ...        ...   
995  ...       0        0        0       0         0        0          0   
996  ...       0        0        0       0         0        0          0   
997  ...       0        0        0       0         0        0          0   
998  ...       0        0        0       0         0        0          0   
999  ...       0        0        0       0         0        0          0   

     판타지 액션  판타지 음악  판타지 코미디  
0         0       0        0  
1         0       0        0  
2         0       0        0  
3         0       0        0  
4         0       0        0  
..      ...     ...      ...  
995       0       0        0  
996       0       0        0  
997       0       0        0  
998       0       0        0  
999       0       0        0  

[1000 rows x 198 columns]

In [15]:
# 사이킷런의 cosine_similarity() 함수를 이용해 코사인 유사도 계산

from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)

print(genre_sim.shape) # 유사도 행렬의 크기
print(genre_sim[:10]) # 2개행만 확인


(1000, 1000)
[[1.  0.  0.4 ... 0.2 0.  0. ]
 [0.  1.  0.  ... 0.  0.8 0.4]
 [0.4 0.  1.  ... 0.2 0.  0. ]
 ...
 [0.2 0.  0.2 ... 0.6 0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.2 0.2 0.2 ... 0.4 0.2 0.4]]


In [16]:
genre_sim

array([[1. , 0. , 0.4, ..., 0.2, 0. , 0. ],
       [0. , 1. , 0. , ..., 0. , 0.8, 0.4],
       [0.4, 0. , 1. , ..., 0.2, 0. , 0. ],
       ...,
       [0.2, 0. , 0.2, ..., 1. , 0. , 0.2],
       [0. , 0.8, 0. , ..., 0. , 1. , 0.4],
       [0. , 0.4, 0. , ..., 0.2, 0.4, 1. ]])

In [33]:
type(genre_sim)

numpy.ndarray

In [20]:
cols = movies_df.movie_id
sim_df = pd.DataFrame(data=genre_sim,columns=cols,index=cols)

In [30]:
sim_df

movie_id   436270    882598    505642   829280    948276    979924    985939   \
movie_id                                                                        
436270    1.000000  0.000000  0.400000      0.0  0.200000  0.000000  0.000000   
882598    0.000000  1.000000  0.000000      0.2  0.200000  0.447214  0.447214   
505642    0.400000  0.000000  1.000000      0.2  0.200000  0.000000  0.000000   
829280    0.000000  0.200000  0.200000      1.0  0.000000  0.000000  0.000000   
948276    0.200000  0.200000  0.200000      0.0  1.000000  0.447214  0.447214   
...            ...       ...       ...      ...       ...       ...       ...   
7555      0.258199  0.258199  0.258199      0.0  0.516398  0.577350  0.577350   
39324     0.400000  0.000000  0.400000      0.0  0.200000  0.000000  0.000000   
101       0.200000  0.000000  0.200000      0.2  0.400000  0.000000  0.000000   
419430    0.000000  0.800000  0.000000      0.2  0.200000  0.447214  0.447214   
43947     0.000000  0.400000  0.000000      0.2  0.200000  0.447214  0.447214   

movie_id   49046    1037858   896485   ...  313297   774021    138103   \
movie_id                               ...                               
436270    0.200000      0.0  0.200000  ...      0.0      0.2  0.200000   
882598    0.000000      0.0  0.200000  ...      0.0      0.2  0.200000   
505642    0.200000      0.0  0.200000  ...      0.2      0.2  0.600000   
829280    0.000000      0.0  0.200000  ...      0.2      0.0  0.200000   
948276    0.400000      0.0  0.400000  ...      0.0      0.2  0.400000   
...            ...      ...       ...  ...      ...      ...       ...   
7555      0.258199      0.0  0.516398  ...      0.0      0.0  0.516398   
39324     0.200000      0.2  0.200000  ...      0.2      0.2  0.200000   
101       0.600000      0.0  0.400000  ...      0.0      0.2  0.200000   
419430    0.000000      0.0  0.200000  ...      0.0      0.2  0.200000   
43947     0.000000      0.0  0.400000  ...      0.0      0.2  0.200000   

movie_id  1427      754609    7555      39324     101       419430    43947    
movie_id                                                                       
436270        0.2  0.000000  0.258199  0.400000  0.200000  0.000000  0.000000  
882598        0.0  0.000000  0.258199  0.000000  0.000000  0.800000  0.400000  
505642        0.0  0.000000  0.258199  0.400000  0.200000  0.000000  0.000000  
829280        0.2  0.000000  0.000000  0.000000  0.200000  0.200000  0.200000  
948276        0.2  0.258199  0.516398  0.200000  0.400000  0.200000  0.200000  
...           ...       ...       ...       ...       ...       ...       ...  
7555          0.0  0.000000  1.000000  0.258199  0.258199  0.258199  0.258199  
39324         0.0  0.000000  0.258199  1.000000  0.200000  0.000000  0.000000  
101           0.4  0.258199  0.258199  0.200000  1.000000  0.000000  0.200000  
419430        0.0  0.000000  0.258199  0.000000  0.000000  1.000000  0.400000  
43947         0.2  0.000000  0.258199  0.000000  0.200000  0.400000  1.000000  

[1000 rows x 1000 columns]

In [32]:
sim_df.to_csv('./sim_df2.csv',  index = True, encoding="utf-8-sig")

In [34]:
genre_sim.argsort()[:, ::-1]

array([[  0, 168, 342, ..., 619, 616, 999],
       [692, 927, 141, ..., 588, 587,   0],
       [248, 530, 636, ..., 529, 527, 499],
       ...,
       [997, 569, 805, ..., 374, 752, 499],
       [998,  11, 354, ..., 588, 587,   0],
       [999, 987, 825, ..., 578, 577,   0]], dtype=int64)

In [35]:
genre_sim.argsort()[:, ::-1][0]

array([  0, 168, 342, 366, 151, 666, 537, 125,  33, 522, 959,  47, 174,
       373, 795, 109, 605, 765, 939, 128, 578, 131, 259, 319, 382, 715,
       157, 177, 929, 802, 500, 948, 523, 487, 648, 609, 244, 120, 789,
       567, 370,  40, 809, 703, 607, 359, 431, 139,  26, 699, 894, 242,
       986, 300, 449, 672, 240, 223, 674, 236, 235, 234, 685, 708, 688,
       689, 706, 759, 712, 784, 840, 838, 837, 134, 827, 816, 147, 150,
       800, 798, 164, 216, 779, 773, 769, 767, 758, 181, 195, 728, 724,
       722, 665, 284, 248, 657, 348, 357, 519, 515, 513, 491, 488, 378,
       480, 478, 389, 466, 463, 461, 460, 455, 395, 398, 446, 403, 405,
       436, 408, 434, 433, 410, 426, 530, 347, 344, 286, 649, 640, 636,
       268, 631, 630, 271, 628, 273, 622, 618, 611, 597, 343, 595, 594,
       592, 315, 571, 328, 330, 557, 555, 553, 547, 341, 843, 711, 882,
       978, 896, 114, 892, 952,  29, 957,  27,  14, 884,  69,  90, 102,
        16,  91,  17,  22,  94,  21,  37,  96,  38, 930, 921, 85

In [37]:
movies_df.loc[[0]]

movie_id  title release_date  popularity  vote_count  vote_average  \
0    436270  블랙 아담   2022-10-19   17020.709        1227           6.8   

                                            overview  \
0  기원전 가장 번성하고 위대한 고대 국가였지만 현재는 국제 군사 조직 인터갱의 독재 ...   

                        poster_path         genres genres_literal  
0  /mEdMHGy1FfCUc7PskFO0tibm8jp.jpg  [28, 14, 878]      액션 판타지 SF

In [36]:
movies_df.loc[[168,342]]

movie_id      title release_date  popularity  vote_count  vote_average  \
168    399566  고질라 VS. 콩   2021-03-24     238.613        8356           7.7   
342    601796    외계+인 1부   2022-07-20     143.161          70           7.3   

                                              overview  \
168  콩과 보호자들은 정착할 수 있는 곳을 찾아 특별하고 강력한 유대감을 형성하고 있는 ...   
342  2022년 현재, 가드와 썬더는 인간의 몸에 가두어진 외계인 죄수를 관리하며 지구에...   

                          poster_path             genres genres_literal  
168   /sqo672rKMXiLRC5kVcGvBRebkp.jpg      [28, 14, 878]      액션 판타지 SF  
342  /i011PWRJcIVe8d9DscLagjRFuXd.jpg  [28, 14, 878, 12]   액션 판타지 SF 모험

In [38]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]

In [39]:
print(genre_sim_sorted_ind[:1])

[[  0 168 342 366 151 666 537 125  33 522 959  47 174 373 795 109 605 765
  939 128 578 131 259 319 382 715 157 177 929 802 500 948 523 487 648 609
  244 120 789 567 370  40 809 703 607 359 431 139  26 699 894 242 986 300
  449 672 240 223 674 236 235 234 685 708 688 689 706 759 712 784 840 838
  837 134 827 816 147 150 800 798 164 216 779 773 769 767 758 181 195 728
  724 722 665 284 248 657 348 357 519 515 513 491 488 378 480 478 389 466
  463 461 460 455 395 398 446 403 405 436 408 434 433 410 426 530 347 344
  286 649 640 636 268 631 630 271 628 273 622 618 611 597 343 595 594 592
  315 571 328 330 557 555 553 547 341 843 711 882 978 896 114 892 952  29
  957  27  14 884  69  90 102  16  91  17  22  94  21  37  96  38 930 921
  850 119 919   2 996 118  61 471 292 291 387 516 509 512 719 739 362 503
  365 968  48 924 464 212 573  79 439 305 148 893 899 548 873 560 828 953
  263 418 956 335 279 375  81  35 684 215  45 698 709 697 845 443 799 393
  380 432 797 484 617 623 593 170  74 

In [45]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    
    # 인자로 전달된 title에 해당되는 데이터 추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 
    # 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임. 
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    # index에 해당되는 데이터프레임 반환
    return df.iloc[similar_indexes]

In [48]:
similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, '블랙 아담',10)

[[  0 168 342 366 151 666 537 125  33 522]]


In [50]:
similar_movies

movie_id                                  title release_date  popularity  \
0      436270                                  블랙 아담   2022-10-19   17020.709   
168    399566                              고질라 VS. 콩   2021-03-24     238.613   
342    601796                                외계+인 1부   2022-07-20     143.161   
366     39107  드래곤볼 Z: 부활의 퓨전!! 손오공과 베지터! (구극장판 12기)   1995-03-04     122.595   
151    761898         소드 아트 온라인 -프로그레시브- 별 없는 밤의 아리아   2021-10-30     241.514   
666    268896                            퍼시픽 림: 업라이징   2018-03-21      94.862   
537    890656                                    벤전스   2022-02-17     118.711   
125    791373                        잭 스나이더의 저스티스 리그   2021-03-18     313.837   
33      19995                                    아바타   2009-12-15     809.146   
522     22894                                     리전   2010-01-21     123.843   

     vote_count  vote_average  \
0          1227           6.8   
168        8356           7.7   
342          70           7.3   
366         677           7.4   
151         117           8.2   
666        4172           6.1   
537         226           5.6   
125        8325           8.2   
33        26573           7.5   
522        2210           5.8   

                                              overview  \
0    기원전 가장 번성하고 위대한 고대 국가였지만 현재는 국제 군사 조직 인터갱의 독재 ...   
168  콩과 보호자들은 정착할 수 있는 곳을 찾아 특별하고 강력한 유대감을 형성하고 있는 ...   
342  2022년 현재, 가드와 썬더는 인간의 몸에 가두어진 외계인 죄수를 관리하며 지구에...   
366  지옥의 악한 영혼 정화통을 관리하는 붉은 오니가 음악에 심취해서 딴청피우다가 정화통...   
151  그날, '너브기어' 를 우연히 머리에 쓴 '유우키 아스나' 는  원래 인터넷 게임과...   
666  전 세계를 초토화시켰던 전쟁 이후, 지구 종말의 위기가 다시 찾아온다.  더 강렬하...   
537  초능력을 지닌 자객 카이. 살인자를 찾아 방콕까지 날아왔다. 개인적인 복수를 위한 ...   
125  슈퍼맨이 죽고 지구에 어둠의 그림자가 드리운다. 마더박스를 차지하기 위해 빌런 스테...   
33   가까운 미래, 지구는 에너지 고갈 문제를 해결하기 위해 머나먼 행성 판도라에서 대체...   
522  12월 23일 새벽 1시 2분 로스엔젤레스에 한 남자가 떨어진다. 그리고 그를 추척...   

                          poster_path             genres   genres_literal  
0    /mEdMHGy1FfCUc7PskFO0tibm8jp.jpg      [28, 14, 878]        액션 판타지 SF  
168   /sqo672rKMXiLRC5kVcGvBRebkp.jpg      [28, 14, 878]        액션 판타지 SF  
342  /i011PWRJcIVe8d9DscLagjRFuXd.jpg  [28, 14, 878, 12]     액션 판타지 SF 모험  
366  /gDyeuYO67gO6raEfQQuWoEbg6Qt.jpg  [16, 28, 14, 878]  애니메이션 액션 판타지 SF  
151  /66Vx0C2cVL0mym0tfKgF4gmcuhA.jpg  [16, 28, 14, 878]  애니메이션 액션 판타지 SF  
666  /3HNCO7bLihIj1icRL9RLPY215KW.jpg  [28, 14, 878, 12]     액션 판타지 SF 모험  
537  /3cccEF9QZgV9bLWyupJO41HSrOV.jpg           [28, 14]           액션 판타지  
125   /qd7iPB26bwMPZqRcnflzAeDkMn.jpg  [28, 12, 14, 878]     액션 모험 판타지 SF  
33   /zygmx5abXeDpr3fWYX4jlXFZ1wh.jpg  [28, 12, 14, 878]     액션 모험 판타지 SF  
522  /ykocDqwg5PRUopnBVb1x1DWnEJF.jpg       [27, 28, 14]        공포 액션 판타지